# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a1f69c60863af540429ae5a0623ed763"
name = "AI Agent Product search"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://localhost:3000/auth/callback",
  "https://localhost:3000/auth/shopify/callback"
]
